---
name: Helm Lint
on:
  # `ct lint` does not work well with tag references on releases.
  # OTOH, Helm linting on tags is not necessary so long as it
  # happens on push to branches.
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.ref_name }} --config ./charts/ct.yaml
